# Generated by Django 6.1 on 2026-09-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph_1', models.TextField()),
                ('paragraph_2', models.TextField()),
                ('stat_1_number', models.CharField(default='2+', max_length=10)),
                ('stat_1_label', models.CharField(default='Years Exp.', max_length=50)),
                ('stat_2_number', models.CharField(default='2', max_length=10)),
                ('stat_2_label', models.CharField(default='Companies', max_length=50)),
                ('stat_3_number', models.CharField(default='10+', max_length=10)),
                ('stat_3_label', models.CharField(default='Technologies', max_length=50)),
                ('stat_4_number', models.CharField(default='100%', max_length=10)),
                ('stat_4_label', models.CharField(default='Dedication', max_length=50)),
            ],
            options={
                'verbose_name': 'About Content',
                'verbose_name_plural': 'About Content',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('period', models.CharField(help_text='e.g., 2024 - Present', max_length=50)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0, help_text='Chini ndio ya kwanza kuonyeshwa')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experience',
                'ordering': ['-order'],
            },
        ),
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designed_by', models.CharField(default='Designed & Built by Brian Gasto Mrema', max_length=100)),
                ('copyright', models.CharField(default='© 2026 Random Tech Solution & Obrigado Solutions. All rights reserved.', max_length=200)),
            ],
            options={
                'verbose_name': 'Footer Settings',
                'verbose_name_plural': 'Footer Settings',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Brian Gasto Mrema', max_length=100)),
                ('title', models.CharField(default='Software Developer | Founder | Technical Director', max_length=100)),
                ('email', models.EmailField(default='mremagastobrian@gmail.com', max_length=254)),
                ('phone', models.CharField(default='0613 950 508', max_length=20)),
                ('location', models.CharField(default='Mbeya, Tanzania', max_length=100)),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='cv/')),
                ('hero_greeting', models.CharField(default='Hello, I am', max_length=50)),
                ('hero_bio', models.TextField(default='Passionate software developer specializing in web development, business systems, and digital solutions.')),
            ],
            options={
                'verbose_name': 'Profile Settings',
                'verbose_name_plural': 'Profile Settings',
            },
        ),
        migrations.CreateModel(
            name='SectionTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_key', models.CharField(help_text='e.g., about, skills, experience', max_length=50, unique=True)),
                ('number', models.CharField(help_text='e.g., 01, 02', max_length=5)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('linkedin', 'LinkedIn'), ('github', 'GitHub'), ('twitter', 'Twitter/X'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp')], max_length=50)),
                ('url', models.URLField()),
                ('icon_class', models.CharField(help_text='e.g., fab fa-linkedin', max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Social Link',
                'verbose_name_plural': 'Social Links',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-featured', 'order']},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='company',
            name='role_title',
            field=models.CharField(default='Founder & Technical Director', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='tagline',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='icon_class',
            field=models.CharField(default='fas fa-check-circle', max_length=50),
        ),
        migrations.AddField(
            model_name='skill',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
