# Generated by Django 6.1 on 2026-09-03 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aboutcontent_experience_footersettings_profile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_greeting', models.CharField(default='Hello, I am', max_length=50)),
                ('hero_name', models.CharField(default='Brian Gasto Mrema', max_length=100)),
                ('hero_subtitle', models.CharField(default='Software Developer | Founder | Technical Director', max_length=150)),
                ('hero_description', models.TextField(default='Passionate software developer specializing in web development, business systems, and digital solutions.')),
                ('cv_file', models.FileField(blank=True, help_text='Upload your CV here (PDF)', null=True, upload_to='cv/')),
                ('about_paragraph_1', models.TextField(default='I am a dedicated Software Developer with almost 2 years of experience, holding a Diploma in Computer Science.', verbose_name='About Paragraph 1')),
                ('about_paragraph_2', models.TextField(blank=True, default='Beyond coding, I am the Founder and Technical Director of two emerging tech companies in Tanzania.', verbose_name='About Paragraph 2')),
                ('contact_email', models.EmailField(default='mremagastobrian@gmail.com', max_length=254)),
                ('contact_phone', models.CharField(default='0613950508', max_length=20)),
                ('contact_location', models.CharField(default='Mbeya, Tanzania', max_length=100)),
                ('linkedin_url', models.URLField(blank=True, default='https://www.linkedin.com/in/briangasto')),
                ('github_url', models.URLField(blank=True, default='https://github.com/kocha-design')),
            ],
            options={
                'verbose_name': 'Website Setting',
                'verbose_name_plural': 'Website Settings',
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='e.g., 2+, 100%', max_length=20)),
                ('label', models.CharField(help_text='e.g., Years Exp.', max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Lower number appears first')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_role', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AboutContent',
        ),
        migrations.DeleteModel(
            name='FooterSettings',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='SectionTitle',
        ),
        migrations.DeleteModel(
            name='SocialLink',
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={},
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={},
        ),
        migrations.RemoveField(
            model_name='company',
            name='role_title',
        ),
        migrations.RemoveField(
            model_name='company',
            name='tagline',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='project',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='project',
            name='order',
        ),
        migrations.RemoveField(
            model_name='service',
            name='icon_class',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='order',
        ),
        migrations.AddField(
            model_name='experience',
            name='is_current',
            field=models.BooleanField(default=False, help_text='Check if this is your current role'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(blank=True, default='Portfolio Contact', max_length=200),
        ),
        migrations.AlterField(
            model_name='experience',
            name='order',
            field=models.IntegerField(default=0, help_text='Lower number appears first'),
        ),
    ]
