# Generated by Django 6.1 on 2026-09-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings_stat_testimonial_delete_aboutcontent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['order', 'founded_date']},
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-is_featured', 'order']},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['company', 'order']},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['order', 'name'], 'verbose_name_plural': 'Skills'},
        ),
        migrations.AlterModelOptions(
            name='stat',
            options={'ordering': ['order'], 'verbose_name_plural': 'Stats'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='excerpt',
            field=models.CharField(blank=True, help_text='Muhtasari mfupi wa article', max_length=300),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='companies/logos/'),
        ),
        migrations.AddField(
            model_name='company',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='website_url',
            field=models.URLField(blank=True, help_text='Official website (optional)'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Onyesha kwenye featured section?'),
        ),
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, default='fa-check-circle', help_text='Font Awesome icon class', max_length=50),
        ),
        migrations.AddField(
            model_name='service',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Facebook profile URL (optional)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_copyright',
            field=models.CharField(default='© 2026 Random Tech Solution & Obrigado Solutions. All rights reserved.', help_text='Text ya chini ya footer (Copyright...)', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_credit',
            field=models.CharField(default='Designed & Built by Brian Gasto Mrema', help_text='Text ya juu ya footer (Designed by...)', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_extra_text',
            field=models.CharField(blank=True, default='', help_text='Maandishi ya ziada kwenye footer (optional)', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_show_social',
            field=models.BooleanField(default=True, help_text='Onyesha social media icons kwenye footer?'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='Twitter/X profile URL (optional)'),
        ),
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.CharField(blank=True, default='fa-code', help_text='Font Awesome icon class, e.g., fa-python', max_length=50),
        ),
        migrations.AddField(
            model_name='skill',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_paragraph_1',
            field=models.TextField(default='I am a dedicated Software Developer with almost 2 years of experience, holding a Diploma in Computer Science. My journey is driven by a passion for creating robust, scalable, and user-centric digital solutions.', verbose_name='About Paragraph 1'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_paragraph_2',
            field=models.TextField(blank=True, default='Beyond coding, I am the Founder and Technical Director of two emerging tech companies, where I lead the vision of delivering top-tier Web Development, Systems Development, Networking, and IT Consultancy services to businesses in Tanzania and beyond.', verbose_name='About Paragraph 2'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='cv_file',
            field=models.FileField(blank=True, help_text='Upload your CV here (PDF format recommended)', null=True, upload_to='cv/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_description',
            field=models.TextField(default='Passionate software developer specializing in web development, business systems, and digital solutions. Experienced in building scalable web applications, management systems, and modern business websites.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_greeting',
            field=models.CharField(default='Hello, I am', help_text='Maneno ya kusalimia (greeting)', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_name',
            field=models.CharField(default='Brian Gasto Mrema', help_text='Jina lako kamili', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_subtitle',
            field=models.CharField(default='Software Developer | Founder | Technical Director', help_text='Cheo chako', max_length=150),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(help_text='e.g., Backend, Frontend, Database, Networking', max_length=50),
        ),
        migrations.AlterField(
            model_name='stat',
            name='label',
            field=models.CharField(help_text='e.g., Years Exp., Companies', max_length=50),
        ),
        migrations.AlterField(
            model_name='stat',
            name='value',
            field=models.CharField(help_text='e.g., 2+, 100%, 10+', max_length=20),
        ),
    ]
